name: Feature Request
description: Suggest a new feature or improvement for Lighthouse AI
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea that would make Lighthouse AI better? We'd love to hear it.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the feature you'd like.
      placeholder: What should Lighthouse AI do?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why do you need this? What problem does it solve for you?
      placeholder: I want this because...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: If you have an idea for how this could work, describe it here.
    validations:
      required: false

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: Have you considered other approaches or workarounds?
    validations:
      required: false
